# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
podfile: Example/Podfile
osx_image: xcode10
#xcode_workspace: Example/FlexibleSteppedProgressBar.xcworkspace
#xcode_scheme: FlexibleSteppedProgressBar-Example
xcode_sdk: iphonesimulator12.0

before_install:
  - gem install xcpretty --no-document --quiet

script:
- set -o pipefail && xcodebuild build -workspace Example/FlexibleSteppedProgressBar.xcworkspace -scheme FlexibleSteppedProgressBar-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
